#!/bin/bash
# 持续迭代循环脚本

echo "🚀 启动持续迭代循环..."

# 迭代任务队列
TASKS=(
    "examples/user-management/src/main/java/com/sdd/user:UserService.java"
    "examples/user-management/src/main/java/com/sdd/user:User.java"
    "examples/user-management/src/main/java/com/sdd/user:CreateUserRequest.java"
    "examples/user-management/src/test/java/com/sdd/user:UserServiceTest.java"
    "templates/feature:feature-template.yaml"
    "templates/api:api-template.yaml"
    "templates/model:model-template.yaml"
    "best-practices/guides:sdd-quick-start.md"
    "best-practices/pitfalls:top-10-mistakes.md"
    "tools/qoder:setup-guide.md"
    "learning-path/beginner:5min-tutorial.md"
    "learning-path/beginner:30min-tutorial.md"
    "community/faq:general.md"
    "community/contribute:how-to-contribute.md"
)

TASK_INDEX=0

while true; do
    # 获取当前任务
    TASK_INFO=${TASKS[$TASK_INDEX]}
    TASK_DIR=$(echo $TASK_INFO | cut -d':' -f1)
    TASK_FILE=$(echo $TASK_INFO | cut -d':' -f2)
    
    echo "📝 迭代 $TASK_INDEX: $TASK_DIR/$TASK_FILE"
    
    # 创建目录
    mkdir -p "$TASK_DIR"
    
    # 根据类型创建内容
    case $TASK_FILE in
        *.java)
            cat > "$TASK_DIR/$TASK_FILE" << 'EOF'
package com.sdd.user;

/**
 * SDD 示例代码
 * 自动迭代生成
 */
public class AutoGenerated {
    // TODO: 实现业务逻辑
}
EOF
            ;;
        *.yaml)
            cat > "$TASK_DIR/$TASK_FILE" << 'EOF'
name: 模板
version: 1.0.0
description: SDD 规范模板

fields:
  - name: 字段
    type: string
    required: true
EOF
            ;;
        *.md)
            cat > "$TASK_DIR/$TASK_FILE" << 'EOF'
# 文档标题

## 概述

[内容待完善]

## 最佳实践

- 实践 1
- 实践 2

## 示例

[示例代码]
EOF
            ;;
    esac
    
    # Git 提交
    git add -A
    git commit -m "feat: 迭代 $TASK_FILE (持续迭代 #$TASK_INDEX)"
    echo "✅ 提交完成 #$TASK_INDEX"
    
    # 汇报（每 5 次）
    if [ $((TASK_INDEX % 5)) -eq 4 ]; then
        echo "📊 进度：已完成 $((TASK_INDEX + 1))/${#TASKS[@]} 个任务"
    fi
    
    # 下一个任务
    TASK_INDEX=$((TASK_INDEX + 1))
    
    # 循环
    if [ $TASK_INDEX -ge ${#TASKS[@]} ]; then
        echo "✅ 第一轮迭代完成，开始第二轮..."
        TASK_INDEX=0
    fi
    
    # 间隔 2 分钟
    sleep 120
done
